.onAttach <- function(libname, pkgname) {
  message("DISCLAIMER - PLEASE READ PRIOR TO USE: \n
  The hydroepixr model is for use by professionals trained in aquatic animal
  health (e.g., veterinarians and fish health managers) and provides information
  to assist decision-making related to waterborne spread of fish pathogens.
  While every effort is taken to ensure soundness of model results, model
  outputs will depend on parameter values selected by users and whether
  they correctly reflect management practices and mitigations used on fish
  farms. The model does not provide predictions of events. By using this tool,
  the user agrees that the authors cannot be held responsible for decisions
  made based on any information generated by the model.\n
  Note that this package is distributed under the GNU GPLv3. This stipulates
  that no closed versions of this package may be distributed, regardless of
  modifications made to the code. For additional details on the GNU GPLv3
  license, view the enter `packageDescription(\"hydroepixr\")$License` in the
  console.")
}
